export const BORDER_RADIUS = 2
export const BORDER_RADIUS_LARGE = 6
export const TEXT_COLOR = '#ddd'
export const BOX_SHADOW = '0 0 0px rgba(0, 0, 0, 0.4)'
export const BOX_SHADOW_LARGE = '0 0 0px rgba(0, 0, 0, 0.4)'
export const HIGHLIGHT = 'rgba(0, 0, 0, 0.2)'
export const BG_DARK = 'rgba(20, 20, 20, 0.9)'
export const BG_HIGHTLIGHT = 'rgba(30, 30, 30, 0.9)'
export const TRANSITION = '0.5s'
export const QUICK_TRANSITION = '0.2s'
export const MIN_SCROLL_AMOUNT = 20
export const MOBILE_CUTOFF = 700
export const DARKEN = 0.3
